train:
  seed: 0
  epochs: 10
  batch_size: 1000
  # accum_grad: 1
  output: runs

  metric:
    monitor: acc_val
    mode: max
    patience: 10

  ema:
    beta: 0.99
    update_after_step: 0
    update_every: 20

  optimizer:
    type: SGD
    lr0: 0.1  # initial learning rate
    lrf: 0.01  # final OneCycleLR learning rate (lr0 * lrf)
    kwargs:
      weight_decay: 0.0001  # optimizer weight decay


augment:
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4  # image HSV-Value augmentation (fraction)

  gb_kernel: 5  # kernel_size of GuassianBlur

  flipud: 0.  # image flip up-down (probability)
  fliplr: 0.5  # image flip left-right (probability)
