fixed_layers: [ -2 ]
depth_multiple: 1.0
width_multiple: 1.0
img_size: 512
drop_pos: [ 2, 4, 6 ]

architecture:
  # [from, number, module, args]
  [ [ -1, 3, PyramidViT, [ 64, 7, 4, 8, 8, 1 ] ],
    [ -1, 4, PyramidViT, [ 128, 3, 2, 4, 8, 2 ] ],
    [ -1, 1, DropBlock, [ 3, 0.3 ] ],

    [ -1, 6, PyramidViT, [ 320, 3, 2, 2, 4, 5 ] ],
    [ -1, 1, DropBlock, [ 3, 0.3 ] ],

    [ -1, 3, PyramidViT, [ 512, 3, 2, 1, 4, 8 ] ],
    [ -1, 1, DropBlock, [ 3, 0.3 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 6, 1 ] ],
    [ -1, 1, Flatten, [ ] ]
  ]
